# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='isadmin',
        ),
    ]
