# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0002_remove_systemuser_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
    ]
