# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0003_systemuser_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='isadmin',
            field=models.CharField(max_length=64),
        ),
    ]
