# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0006_auto_20181022_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemuser',
            old_name='isadmin',
            new_name='is_admin',
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
