# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0009_eteamshost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eteamshost',
            name='hostdesc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
