# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-24 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0011_auto_20181023_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty', models.CharField(max_length=1)),
            ],
        ),
    ]
