# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-26 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0012_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host2HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostgroupname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmanager.EteamsHost')),
            ],
        ),
        migrations.AddField(
            model_name='host2hostgroup',
            name='hostgroupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmanager.HostGroup'),
        ),
        migrations.AddField(
            model_name='host2hostgroup',
            name='hostid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmanager.EteamsHost'),
        ),
    ]
