# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-26 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0013_auto_20181026_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='hostgroupname',
            field=models.CharField(max_length=64),
        ),
    ]
