# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-09 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0014_auto_20181026_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=64)),
                ('port', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=64)),
                ('inhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmanager.EteamsHost')),
            ],
        ),
    ]
