# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0015_servicemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirname', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=256)),
                ('doc', models.TextField(max_length=4096)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmanager.SystemUser')),
                ('docdir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmanager.DocumentDir')),
            ],
        ),
        migrations.RemoveField(
            model_name='jumpserveraccountmanager',
            name='serveraccount',
        ),
        migrations.RemoveField(
            model_name='jumpserveraccountmanager',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='serveraccount',
            name='hostid',
        ),
        migrations.DeleteModel(
            name='JumpServerAccountManager',
        ),
        migrations.DeleteModel(
            name='ServerAccount',
        ),
    ]
