# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0016_auto_20181114_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
