# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-18 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0018_servicemanager_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeployStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=64)),
                ('status', models.BooleanField(default=False)),
                ('lastdeploytime', models.DateTimeField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmanager.ServiceManager')),
            ],
        ),
    ]
