# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0019_servicedeploystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedeploystatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
