# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0020_auto_20181219_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeployConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=256)),
                ('lastpackagetime', models.DateTimeField(null=True)),
                ('projectname', models.CharField(max_length=256)),
                ('imagename', models.CharField(max_length=512)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmanager.ServiceManager')),
            ],
        ),
        migrations.AlterField(
            model_name='servicedeploystatus',
            name='desc',
            field=models.CharField(max_length=256),
        ),
    ]
