# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0023_imagelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedeployconfig',
            name='imagename',
        ),
        migrations.AddField(
            model_name='servicedeployconfig',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostmanager.ImageList'),
            preserve_default=False,
        ),
    ]
