# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-24 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0024_auto_20181221_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeployList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmanager.ServiceManager')),
            ],
        ),
    ]
