# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-25 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0026_auto_20181224_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedeploylist',
            name='status',
            field=models.CharField(default='wait', max_length=64),
            preserve_default=False,
        ),
    ]
