# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-25 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0027_servicedeploylist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedeploylist',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
