# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-26 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0028_servicedeploylist_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedeployconfig',
            name='lastpackagetime',
        ),
        migrations.AlterField(
            model_name='servicedeploylist',
            name='status',
            field=models.CharField(default='wait', max_length=64),
        ),
    ]
