# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-26 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanager', '0029_auto_20181226_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptsExecStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptname', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
